// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backendcflopes.Data;

namespace backendcflopes.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221009024921_novastabelas")]
    partial class novastabelas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("backendcflopes.Models.Calculo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ativo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("comissao_pasch")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("data_inserido")
                        .HasColumnType("TEXT");

                    b.Property<double>("juros_simples")
                        .HasColumnType("REAL");

                    b.Property<double>("juros_total")
                        .HasColumnType("REAL");

                    b.Property<string>("nome_campanha")
                        .HasColumnType("TEXT");

                    b.Property<double>("porcentagem_desconto_permitido")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("Calculos");
                });
#pragma warning restore 612, 618
        }
    }
}
